In [163]:
import numpy as np
import pandas as pd
import tensorflow  as tf

print(tf.__version__)

2.16.1


In [164]:
ds= pd.read_csv("Churn_Modelling.csv")

X=ds.iloc[:,3:-1].values
y=ds.iloc[:,-1].values

print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [165]:
from sklearn.preprocessing import  LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])
print(X) #Female - 0 Male -1 

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [166]:
from sklearn.compose import  ColumnTransformer
from sklearn.preprocessing import  OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X=X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [167]:
from sklearn.model_selection import  train_test_split as tts
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=0)

print(X_train)
print(X_test)
# print(y_train)
# print(y_test)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]
[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [168]:

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
print(X_test)


[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


#### Building the ANN

In [169]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation="relu")) #First hidden Layer with 6 neurons




In [170]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu")) #second hidden Layer with 6 neurons

In [171]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid")) #output hidden Layer with 6 neurons {if non binary outcome use softmax funciton instead of sigmoid}

In [172]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) # Compiling the ANN

In [173]:
ann.fit(X_train, y_train, batch_size = 82, epochs = 100) # Training the  ANN

Epoch 1/100


98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.4150 - loss: 0.8175
Epoch 2/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7511 - loss: 0.5844
Epoch 3/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7962 - loss: 0.5011
Epoch 4/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7913 - loss: 0.4834
Epoch 5/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7981 - loss: 0.4670
Epoch 6/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7999 - loss: 0.4531
Epoch 7/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.8066 - loss: 0.4439
Epoch 8/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8091 - loss: 0.4381 
Epoch 9/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.8089 - loss: 0.4353
Epoch 10/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8207 - loss: 0.4208
Epoch 11/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.8148 - loss: 0.4340
Epoch 12/100
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step 

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [174]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

In [175]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [176]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   83]
 [ 186  219]]


0.8655